#!/usr/bin/env python3

import RPi.GPIO as gpio
import requests
import time

gpio.setmode(gpio.BCM)

gpio.setup(17, gpio.OUT)

try:
    print("Dis-arming alarm...")
    gpio.output(17, gpio.LOW)
    time.sleep(1)
    print("Alarm dis-armed!")
finally:
    gpio.output(17, gpio.HIGH)

