all: open_door_shim reload_asterisk_shim arm_alarm_shim
open_door_shim:
	gcc open_door_shim.c -o open_door_shim

reload_asterisk_shim:
	gcc reload_asterisk_shim.c -o reload_asterisk_shim

arm_alarm_shim:
	gcc arm_alarm_shim.c -o arm_alarm_shim
